credentials:
  usernames:
    ratan:
      email: ratan@example.com
      name: Ratan
      password: "$2b$12$MWg3wY0mT6j5i5K9XQzS2uP9jP8kM4N9x8VqWjM2bM5Y8xQw0s8aK"

cookie:
  expiry_days: 30
  key: random_signature_key
  name: ratan_quant_terminal

preauthorized:
  emails:
    - ratan@example.com
